/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:7b4ffe13-5eb7-4d03-9f1b-e21f4f8a53ac",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_dn8yFcytr",
    "aws_user_pools_web_client_id": "6sm43dd4i1hkaveh9abe5d3dec",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "s3techxreactnative-02192023143850-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
